### ISSUE TITLE
Is the example capabilities out of sync w/ the Selenium Wizard?

### ISSUE THREAD

**Issue by bartonhammond** [crossbrowsertesting/selenium-php#2]
Using the provided example has these capabilities:
```
        $capabilities = array("name"=> "Selenium Test Example",
                              "build"=> "1.0",
                              "browser_api_name"=> "FF46",
                              "os_api_name"=> "Win10",
                              "record_video"=> "true",
                              "take_snapshot"=> "true",
                              "record_network"=> "true",);
```
The documentation says to use the "Selenium Wizard" (https://app.crossbrowsertesting.com/selenium/run) for capabilities.  

When I use that wizard for `javascript` (there is no PHP option?), for "Win10" and FireFox 46, the caps are:

```
var caps = {
    'browserName': 'Firefox',
    'version': '46',
    'platform': 'Windows 10',
    'screenResolution': '1366x768'};
```
Why the difference? Which is correct? Does the example need to be updated?

Where is the documentation for **all** the `capabilities`?

**Comment by lkende** [comment]
@bartonhammond Yes.  These example files have been sorely neglected.  We have changed our capabilities to match standard selenium capabilities, though we do support these older custom capabilities.  This was relatively recent and have not updated all the GitHub examples.

[See the full capabilities here.](https://help.crossbrowsertesting.com/selenium-testing/tutorials/crossbrowsertesting-automation-capabilities/)

We will get these API example scripts up-to-date as well as add PHP to the "wizard" (which doesn't actually exist anymore, it's now the "configurator").

You can find more [PHP examples here](https://github.com/crossbrowsertesting?utf8=%E2%9C%93&q=php&type=&language=).
