### ISSUE TITLE
WebDriverCurlException: Operation timed out after 29848 milliseconds

### ISSUE THREAD

**Issue by bartonhammond** [crossbrowsertesting/selenium-php#3]
My Fork for a PR (https://github.com/bartonhammond/selenium-php) has the code used here.  

What can I do about this?

```
composer run_tests
> ./vendor/bin/phpunit ./php_example.php  2>&1 | tee ./tests.log
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 30.03 seconds, Memory: 4.00MB

There was 1 error:

1) ToDoTest::testToDos
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"name":"Selenium Test Example","build":"1.0","browserName":"Firefox","version":"55x64","platform":"Windows 10","record_video":"true","take_snapshot":"true","record_network":"true"}}

Operation timed out after 29848 milliseconds with 0 bytes received

/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:286
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/php_example.php:68

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by bartonhammond** [comment]
I updated the  `create` parameters for time outs and still w/ 100 seconds, it times out
Code: 
```
        $this->driver = RemoteWebDriver::create($host, $capabilities, 100000, 100000 );
```
Log: 
```
1) ToDoTest::testToDos
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"name":"Selenium Test Example","build":"1.0","browserName":"Firefox","version":"55x64","platform":"Windows 10","record_video":"true","take_snapshot":"true","record_network":"true"}}

Operation timed out after 99855 milliseconds with 0 bytes received

/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:286
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/php_example.php:69

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
~/projects/wisnet/gitProjects/selenium-php-
```

**Comment by lkende** [comment]
Is this consistent?  It timed out creating the session which occasionally can happen but shouldn't be consistent.  If it is, then it could indicate another problem.

**Comment by bartonhammond** [comment]
I just ran both versions.  The time occurs both with updated Capabilities and the original `php_example.php`.  

Note that the original php times out after the default length of `30 seconds`.  The PR version timed out after `1.66 minutes`

From my PR branch : 
```
composer run_tests
> ./vendor/bin/phpunit ./php_example.php  2>&1 | tee ./tests.log
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 1.66 minutes, Memory: 4.00MB

There was 1 error:

1) ToDoTest::testToDos
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"name":"Selenium Test Example","build":"1.0","browserName":"Firefox","version":"55x64","platform":"Windows 10","record_video":"true","take_snapshot":"true","record_network":"true"}}

Operation timed out after 99458 milliseconds with 0 bytes received

/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:286
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/Users/barton/projects/wisnet/gitProjects/selenium-php-pr/php_example.php:69

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

From original code:
```
vendor/bin/phpunit php_example.php 
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

E

Time: 30.05 seconds, Memory: 4.00MB

There was 1 error:

1) ToDoTest::testToDos
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"name":"Selenium Test Example","build":"1.0","browser_api_name":"FF46","os_api_name":"Win10","record_video":"true","take_snapshot":"true","record_network":"true"}}

Operation timed out after 29860 milliseconds with 0 bytes received

/Users/barton/projects/wisnet/gitProjects/selenium-php/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:92
/Users/barton/projects/wisnet/gitProjects/selenium-php/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
/Users/barton/projects/wisnet/gitProjects/selenium-php/vendor/facebook/webdriver/lib/Remote/RemoteWebdriver.php:100
/Users/barton/projects/wisnet/gitProjects/selenium-php/php_example.php:26

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by lkende** [comment]
Looks like we have an issue with Windows 10 and Firefox.  We are working on getting that corrected.  This works on Windows 8.1 instead.  I'll let you know when the issues is corrected.

**Comment by bartonhammond** [comment]
Hi Luke,

I'm  not able to test as I've "used all of the Automated minutes available
on your Free Trial."  We are evaluating CBT as we consider moving away from
BrowserStack.  But before we cancel BS I'd like to know that I can run our
PhpUnit Tests on CBT.  I think I lost a lot of test time due to this error
here.

Is there any way we can extend my testing time?

Thanks,

Barton

**Comment by lkende** [comment]
Barton,

I am happy to extend your testing time.   Note that no minutes are used on these error cases.  The session would actually have to launched in order for minutes to be counted toward your account.  

I need to verify I have the correct account... your domain is 'acclivyx', correct?

**Comment by lkende** [comment]
Also, the Windows 10 Firefox issue is corrected now.  Thanks for reporting!

**Comment by bartonhammond** [comment]
Hi Luke,

my email domain is "acclivyx".  For full disclosure, I also have a "
bhammond@wisnet.com" which is the company I work for but that also has run
out of time.

I'm very encouraged w/ CBT  support / responsiveness.  What i want to do
before having our company purchase "Unlimited Testing" is to confirm I can
run our current PhpUnit tests.  I think I might get that done today before
I leave at 2pm.

Though our company will be on vacation for Thurs/Fri, I'd like to continue
my work w/o running out of minutes if possible. If I can get my tests run,
I'm pretty sure we'll purchase "Unlimited Testing" today.

Thanks,

-b

**Comment by lkende** [comment]
Barton, 

We'll keep your free trial going as needed. The limitations are there for people that abuse our system not for your case.  We want you to be able to adequately test the services.

I've set your free trial (acclivyx account) to 600 automated and 600 manual minutes (instead of the default 100 minutes).  I've also removed the limitation on Operating Systems and browsers you can test on - you now have full access.  Refresh your app to see the changes reflected but your selenium tests will now work.

Your trial still expires on 11/28/2017, but we can extend the time if you need it.  Just let us know.  If so, we'd prefer you to email us at support@crossbrowsertesting.com instead of keeping all of our communications over github issues ;)  You can CC me luke@crossbrowsertesting.com.

I'm glad you are considering moving to our service.  The "unlimited" plan is a great choice, but don't hesitate to contact sales@crossbrowsertesting.com if you need a custom solution as we realize is not a one-size-fits all.

One last thing.  In your branch, be careful do not lock down your username and authkey please.

Thanks!

**Comment by bartonhammond** [comment]
Hi Luke,

Thanks for the time bonus.  That should keep me good these next 4 days.

Also "be careful do not lock down your username and authkey please." - yeah
- I caught that too.  So I changed my authkey in my account.

Again, thanks,

-b

**Comment by bartonhammond** [comment]
Working now
